### ISSUE TITLE
Makefile target in README.txt

### ISSUE THREAD

**Issue by ghost** [CAMBADA/cambada-pub#1]
Hello,

Just to signal a problem on the README.txt file.

At some point it says 
- execute "make all tools csim"

And it should be, I think
- execute "make all tools csim-exec"

I have just started to test, but congratulations on the great work.

Miguel

**Comment by johnavlis** [comment]
Hello Miguel.

You are right, the make target is indeed "csim-exec". I will correct the README file soon.

Thank you for your feedback.

João Silva

**Comment by ricdays** [comment]
Hey,

Fixed on 8270ecd8e1d1c70c7e01b7b0913eb46aef9e6b0e
Thanks for reporting Miguel!

Ricardo Dias
